### ISSUE TITLE
OTAV Winglets

### ISSUE THREAD

**Issue by steedcrugeon** [steedcrugeon/REKT#10]
CoL and Cop need adjustment on the OTAV winglets [Port] and [Stbd] parts. The OTAV part should be able to fly/glide relatively predictably without relying on the toqrue wheel.

**Comment by steedcrugeon** [comment]
Revions to CoL and CoP complete. Outstanding issue from 'ignorePitch' setting in ModuleControlSurface of the config for both Port and Starboard parts: https://github.com/linuxgurugamer/RetractableLiftingSurface/issues/2

**Comment by steedcrugeon** [comment]
closed by accident

**Comment by linuxgurugamer** [comment]
Can you be a bit more specific?  Do you expect the ignorePitch on the control surface to carry through to the main part?
Or, maybe I'm missing what you are saying.

**Comment by steedcrugeon** [comment]
> you expect the ignorePitch on the control surface to carry through to the main part

That was my understanding, I thought that by disabling the pitch in the config (as I have done in another part: https://github.com/steedcrugeon/REKT/blob/master/SHED/Parts/OTAV/OTAVmain/OTAVflap.cfg
Then it would disable the pitch for the retractable lifting surface.
Is this interpretation incorrect?

**Comment by linuxgurugamer** [comment]
I don't know, let me do a little research

**Comment by linuxgurugamer** [comment]
Ok.  From what I can tell, ignorePitch is used by exactly 1 stock part, the AeroBrake.
the part also has ignoreRoll set.
No other parts have this set, so it's somewhat hard to figure out.
But, it's defined in the ModuleControlSurface only, I'm not sure what you are trying to do with it.

**Comment by steedcrugeon** [comment]
I just wanted to 'set' it. I'd like the part to have the Pitch switched off by default. That isn't to say that the player couldn't do it themselves in the VAB, I was just hoping to have the part's Pitch disabled as the default. For ModuleRetractableLifitngSurface I have to define the control surface otherwise it won't recognise it. So I am using ModuleControlSurface on that part. It's just a bit weird is all, I wonder if it a stock bug?

**Comment by linuxgurugamer** [comment]
But, if a part doesn't have a control surface, there is no pitch.  Not trying to be difficult, but I'm having a problem understanding how to turn off pitch when there is no pitch to turn off :-)

What happens when you turn off pitch in the VAB?  Can you do a short video or a series of steps I can use to reproduce?

**Comment by steedcrugeon** [comment]
Well I'll be. I'm very sorry to have wasted your time. It seems something was corrupt with my KSP install. one fresh install later and the ModuleControlSurface is now behaving exactly as expected (and I can set the pitch to off by default even with ModuleRetractableLiftingSurface. 
(I was trying to record a screen grab video and discovered it to be working as intended)

Sorry to have wasted your time, thanks for looking into it anyway.
